# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "cucumber"
gem "capybara"
gem "selenium-webdriver"
gem "chromedriver-helper"
gem 'geckodriver-helper'
gem "cpf_faker"
gem "rspec"
gem "site_prism"
gem "ffi"
gem 'rake'
gem 'syntax'
gem 'poltergeist'
gem 'rubocop'
gem 'cucumber_analytics'
gem 'httparty', '~> 0.13.7'
gem 'faker', '~> 1.6', '>= 1.6.6'
gem 'bundler'
gem 'date_format' #docs http://rpatil.github.io/date-format/
gem 'chromedriver-installer', '~> 0.0.6'
gem 'prawn', '~> 2.1'
